# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.1
_src_path: https://github.com/jupyterlab/extension-template
author_email: ''
author_name: intel
data_format: string
file_extension: ''
has_binder: true
has_settings: false
kind: frontend
labextension_name: jupyterlab_slurm_counter
mimetype: ''
mimetype_name: ''
project_short_description: A JupyterLab extension.
python_name: jupyterlab_slurm_counter
repository: ''
test: false
viewer_name: ''

